# Generated by Django 4.0 on 2021-12-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos')),
                ('photo', models.ImageField(upload_to='photos')),
                ('short_info', models.CharField(blank=True, max_length=255)),
                ('main_phone', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('contacts', models.CharField(blank=True, max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=255)),
                ('profile_text', models.TextField(blank=True)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[(1, 'READER'), (2, 'AUTHOR'), (3, 'MODERATOR'), (4, 'ADMIN')], max_length=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='orgstructure.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
        ),
    ]
