# Generated by Django 4.0 on 2021-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('READER', 'Читатель'), ('AUTHOR', 'Автор'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Администратор')], max_length=9),
        ),
    ]
