# Generated by Django 3.2.11 on 2022-01-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('READER', 'Читатель'), ('WRITER', 'Автор'), ('MODERATOR', 'Модератор'), ('ADMIN', 'Администратор')], max_length=9),
        ),
    ]
