# Generated by Django 3.2.11 on 2022-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0005_alter_organization_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
