# Generated by Django 3.2.11 on 2022-04-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Не отвечено (новое)'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='specialist',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='main_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Краткое наименование'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (1 предложение)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ссылка на сайт'),
        ),
    ]
