# Generated by Django 4.0 on 2021-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authorship',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='article_photo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
