# Generated by Django 4.0 on 2021-12-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgstructure', '0002_alter_userprofile_role'),
        ('media', '0003_alter_article_authorship_alter_article_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='orgstructure.userprofile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='articles', to='media.ArticleFile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='articles', to='media.Question'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='articles', to='media.Section'),
        ),
    ]
