# Generated by Django 3.2.11 on 2022-01-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('MODERATION', 'На модерации'), ('REJECTED', 'Отклонено'), ('APPROVED', 'Опубликовано'), ('DELETED', 'Удалено')], default='NEW', max_length=10),
        ),
    ]
