# Generated by Django 3.2.11 on 2022-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20220108_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
