# Generated by Django 3.2.11 on 2022-01-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20220111_1251'),
        ('media', '0010_article_last_edit_date'),
    ]

    operations = [
    ]
