# Generated by Django 3.2.11 on 2022-04-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_merge_20220111_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
